### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by Jake1152** [saveme-cadet/LMS-Frontend#148]
## 오류 사진이나 설명
* 
![image](https://user-images.githubusercontent.com/74135462/200206926-4a424e89-e10e-4e8d-add0-a98b5b8be862.png)

## 발생 위치
* 아오지 시작 시간이 어제 오후 2시 이후 였는데 시작시간은 어제 오후 11시 55분으로 되어있습니다
 또한 삭제가 되지 않습니다.
 

## 해결시도
*

**Comment by mike2ox** [comment]
해당 이슈 진행사항은 관련 오류로 확인되는 #143 에서 확인하시면 되겠습니다.
