### ISSUE TITLE
[Feature] 아오지 페이지

### ISSUE THREAD

**Issue by GulSam00** [saveme-cadet/LMS-Frontend#19]
## 작업할 내용
아오지 페이지
## 해야할 일
- [ ] 종료 시간 수정 기능
- [x] #25
- [x] 총 탕감 시간 계산?
- [x] 아무런 데이터도 없을 때 예외처리 컴포넌트
- [x] 소수점 계산

**Comment by GulSam00** [comment]
빠르게 아오지를 시작하고 종료할 시 DB가 고장나는데,  - differenceInSeconds(now, startTime)으로 계산했을 때 -0이 나왔을 경우가 이에 해당된다. 1초 미만일 경우 POST 못하게 막아두었다.

**Comment by luckylooky2** [comment]
해야 할 일
- [ ] 수정 버튼 모달 띄우기
